from pydantic import BaseModel, Field
from typing import List


class FinancialDataInput(BaseModel):
    monthly_income: float = Field(
        ...,
        description="Monthly income in currency units"
    )

    monthly_debt: float = Field(
        ...,
        description="Monthly debt or EMI obligations"
    )

    credit_limit: float = Field(
        ...,
        description="Total available credit limit across cards"
    )

    credit_used: float = Field(
        ...,
        description="Current total credit card balance used"
    )

    current_cibil_score: int = Field(
        ...,
        description="Current CIBIL score (300 to 900)"
    )

    credit_score_history: List[int] = Field(
        ...,
        description="List of historical CIBIL scores"
    )

    class Config:
        json_schema_extra = {
            "example": {
                "monthly_income": 75000,
                "monthly_debt": 15000,
                "credit_limit": 200000,
                "credit_used": 45000,
                "current_cibil_score": 750,
                "credit_score_history": [680, 710, 730, 750]
            }
        }


class FinancialAnalysisResponse(BaseModel):
    dti_ratio: float = Field(
        ...,
        description="Debt-to-Income ratio in percentage"
    )

    credit_utilization: float = Field(
        ...,
        description="Credit Utilization ratio in percentage"
    )

    current_cibil_score: int = Field(
        ...,
        description="Provided CIBIL score"
    )

    financial_health: str = Field(
        ...,
        description="Overall financial health classification"
    )

    ai_explanation: str = Field(
        ...,
        description="Personalized financial explanation generated by Gemini"
    )

    metrics_summary: dict = Field(
        ...,
        description="Summary of input parameters and key indicators"
    )